version: "3.8"
services:
  devops-java-springboot-color:
    image: "ghcr.io/pagopa/devops-springboot-gitlab-workflow:latest"
    # build:
    #   dockerfile: ./Dockerfile
    #   context: .
    container_name: devops-springboot-gitlab-workflow
    restart: always
    environment:
      - MY_CONFIGMAP_VALUE=1
      - MY_SECRET_VALUE=very secret 1
    ports:
      - "8080:8080"
