version: "3.8"
services:
  devops-java-springboot-color:
    # image: "ghcr.io/pagopa/devops-java-springboot-color:0.6.0"
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: devops-java-springboot-color
    restart: always
    environment:
      - MY_APP_COLOR=red
      - MY_MANDATORY_SECRET="very secret"
      - MY_MANDATORY_VALUE="very value"
    ports:
      - "8080:8080"
