# Source: devops-springboot-gitlab-workflow/charts/microservice-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: devops-springboot-gitlab-workflow-microservice-chart
  namespace: idpay
  labels:
    helm.sh/chart: microservice-chart-1.13.0
    app.kubernetes.io/name: microservice-chart
    app.kubernetes.io/instance: devops-springboot-gitlab-workflow
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-mchart-svc
      protocol: TCP
      name: service
  selector:
    app.kubernetes.io/name: microservice-chart
    app.kubernetes.io/instance: devops-springboot-gitlab-workflow
