# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

parameters:
  - name: 'executeBuild'
    displayName: 'Remove this flag to skip build and proceed to deploy a docker image previously built'
    type: boolean
    default: true

trigger:
  branches:
    include:
      - main
      - release-*
  paths:
    include:
      - app/*
      - core/*
      - integration/*
      - web/*
      - pom.xml

pr: none

resources:
  - repo: self

variables:
#  dockerfileRelativePath: '$(DOCKERFILE)' # Dockerfile

  # Agent VM image name for Build

  vmImageNameDefault: 'ubuntu-latest'
  product: 'devopslab'

  # Image Repository Name
  imageRepository: '$(K8S_IMAGE_REPOSITORY_NAME)'
  deployNamespace: '$(DEPLOY_NAMESPACE)'
  deploymentName: '$(DEPLOYMENT_NAME)'

  environment: 'DEV'
#  dockerRegistryServiceConnection: '$(DEV_CONTAINER_REGISTRY_SERVICE_CONN)'
  kubernetesServiceConnection: '$(DEV_KUBERNETES_SERVICE_CONN)'
#  containerRegistry: '$(DEV_CONTAINER_REGISTRY_NAME)'
  selfHostedAgentPool: test-marco
  mavenGoals: 'package'
#  settingsXmlsecureFileName: '$(SETTINGS_XML_RO_SECURE_FILE_NAME)'

stages:

  - stage: 'Deploy'
    displayName: 'Deploy_to_${{ variables.environment }}'
#    dependsOn: "Publish_artifact_helm"
    condition: or(succeeded(), not(${{ parameters.executeBuild }}) )
#    variables:
#      pomversion: $[ stageDependencies.Release.POM.outputs['getpomversion.outputpomversion'] ]
    jobs:
      - deployment: 'Deploy_to_${{ variables.environment }}'
        displayName: 'Deploy_to_${{ variables.environment }}'
        pool:
          name: $(selfHostedAgentPool)
        environment: '$(environment)'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
#                - task: DownloadPipelineArtifact@2
#                  inputs:
#                    buildType: 'current'
#                    artifactName: 'helm'
#                    targetPath: '$(Pipeline.Workspace)/helm'
                - task: Bash@3
                  displayName: ls
                  name: ls
                  condition: succeeded()
                  inputs:
                    targetType: 'inline'
                    script: |
                      ls -la $(Build.SourcesDirectory)
                    failOnStderr: true
                - task: Bash@3
                  name: helm_dependency_build
                  displayName: Helm dependency build
                  inputs:
                    workingDirectory: '$(Build.SourcesDirectory)/helm/$(product)/$(deployNamespace)'
                    targetType: 'inline'
                    script: |
                      helm repo add pagopa-microservice https://pagopa.github.io/aks-microservice-chart-blueprint
                      helm dep build
                    failOnStderr: true
                - task: HelmDeploy@0
                  displayName: Helm upgrade
                  inputs:
                    kubernetesServiceEndpoint: ${{ variables.kubernetesServiceConnection }}
                    namespace: '$(deployNamespace)'
                    command: upgrade
                    chartType: filepath
                    chartPath: $(Build.SourcesDirectory)/helm/$(product)/$(deployNamespace)
                    chartName: "Chart.yaml"
                    releaseName: ${{ variables.imageRepository }}
                    valueFile: "$(Build.SourcesDirectory)/helm/$(product)/$(deployNamespace)/values-${{ lower(variables.environment) }}.yaml"
                    install: true
                    waitForExecution: true
                    arguments: "--timeout 2m0s --debug"
