---
name: "generate-tag"

on:
  push:
    branches:
      - "main"

jobs:
  generate-tag:
    name: "Generate TAG"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          skip-on-empty: "false"
          skip-commit: "true"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
