---
name: "generate-tag"

on:
  push:
    branches:
      - "main"

jobs:
  generate-tag:
    name: "Generate TAG"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
            persist-credentials: false
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          skip-on-empty: "false"
          # skip-commit: "true"
          github-token: ${{ secrets.github_token }}
          output-file: "false"  

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
