name: Release

on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04

    steps:

      - name: Release action
        id: release
        uses: pagopa/eng-github-actions-iac-template/global/release-action@release-action-outputs #
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: print_ok
        id: print
        if: steps.release.outputs.new_release_published == 'true'
        run: echo "New Release version ${{steps.release.outputs.new_release_version}}"

      - name: print_fail
        id: print_fail
        if: steps.release.outputs.new_release_published == 'false'
        run: echo "No new release"


      # - name: Log in to the Container registry
      #   id: docker_login
      #   if: steps.release.outputs.new_release_published == 'true'
      #   # from https://github.com/docker/login-action/commits/master
      #   uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push Docker image
      #   id: docker_build_push
      #   if: steps.release.outputs.new_release_published == 'true'
      #   # from https://github.com/docker/build-push-action/commits/master
      #   uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       ghcr.io/${{ github.repository }}:latest
      #       ghcr.io/${{ github.repository }}:v${{ steps.release.outputs.new_release_version }}
      #     labels: |
      #       maintainer=https://pagopa.it
      #       org.opencontainers.image.source=https://github.com/${{ github.repository }}
