name: Snapshot docker build and push

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - 'main'
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

jobs:
  release:
    name: Snapshot Docker
    runs-on: ubuntu-22.04
    environment: dev

    steps:
      # - name: Log in to the Github Container registry
      #   id: docker_login
      #   uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 #v3.2.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push Docker image with release version
      #   id: docker_build_push
      #   uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c #v6.3.0
      #   with:
      #     context: .
      #     push: true
      #     tags: "ghcr.io/${{ github.repository }}:snapshot,ghcr.io/${{ github.repository }}:snapshot-${{ github.ref_name }}"
      #     labels: |
      #       maintainer=https://pagopa.it
      #       org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Trigger Azure DevOps pipeline
        uses: jacopocarlini/azure-pipelines@v1.3
        with:
          azure-devops-project-url: 'https://dev.azure.com/pagopaspa/devopslab-projects'
          azure-pipeline-name: 'devopslab-diego-deploy.deploy'
          azure-devops-token: ${{ secrets.AZUREDEVOPS_PAT }}
          azure-template-parameters: |
            {
                "APPS": ["one-color"]
            }
          azure-pipeline-variables: '{"system.debug": "true"}'
