name: Snapshot release feature

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - 'main'
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

jobs:
  release:
    name: Beta docker on dev branch
    runs-on: ubuntu-22.04

    steps:
      - name: Release with docker action
        id: release
        uses: pagopa/eng-github-actions-iac-template/global/docker-build-push@docker-release-choos-folder #
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docker_context_path: "."
          docker_tag_prefix: "my"

