name: Snapshot docker build and push

on:
  push:
    branches-ignore:
      - 'main'
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'
  workflow_dispatch:


env:
  CURRENT_BRANCH: ${{ github.event.inputs.branch || github.ref_name }}

jobs:
  release:
    name: Snapshot Docker
    runs-on: ubuntu-22.04
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CURRENT_BRANCH }}

      - name: Log in to the Github Container registry
        id: docker_login
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 #v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tags
        id: set_docker_tags
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "DOCKER_TAGS=ghcr.io/${{ github.repository }}:develop-latest,ghcr.io/${{ github.repository }}:snapshot" >> $GITHUB_OUTPUT
          else
            echo "DOCKER_TAGS=ghcr.io/${{ github.repository }}:snapshot,ghcr.io/${{ github.repository }}:snapshot-${{ env.CURRENT_BRANCH }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        id: docker_build_push
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c #v6.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.set_docker_tags.outputs.DOCKER_TAGS }}
          labels: |
            maintainer=https://pagopa.it
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Trigger Azure DevOps pipeline
        uses: jacopocarlini/azure-pipelines@v1.3
        with:
          azure-devops-project-url: 'https://dev.azure.com/pagopaspa/devopslab-projects'
          azure-pipeline-name: 'devopslab-diego-deploy.deploy'
          azure-devops-token: ${{ secrets.AZUREDEVOPS_PAT }}
          azure-template-parameters: |
            {
                "APPS": "[one-color]",
                "POSTMAN_BRANCH": "${{ env.CURRENT_BRANCH }}"
            }
          azure-pipeline-variables: '{"system.debug": "true"}'
